services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: testeTecnico
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
  #web:
    #image: teste-tecnico
    #build:
      #context: .
      #dockerfile: Dockerfile
    #ports:
      #- "8080:8080"
    #depends_on:
      #- db